import Head from 'next/head'
import Image from 'next/image'
import DefaultLayout from "../layouts/DefaultLayout";
import { useRouter } from 'next/router'
import MyMain from "../components/MyMain";
import Card from "../components/Card";

import tstImg from '../public/tstImg.jpg'
import HomeLayout from "../layouts/HomeLayout";
import CardList from "../components/CardsList";

export default function Home() {



    return (
    <div>
      <Head>
        <title>Rafl Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            <DefaultLayout>
                <MyMain>
                    <HomeLayout>
                        <CardList/>
                    </HomeLayout>
                </MyMain>
            </DefaultLayout>
    </div>
  )
}
